SEARCHING = "searching"
PENDING_USER_CONFIRMATION = "pending_user_confirmation"
ASSIGNED = "assigned"
ON_THE_WAY = "on_the_way"
ON_SITE = "on_site"
COMPLETED = "completed"
PAID = "paid"

MASTER_ALLOWED_STATUSES = {
    ASSIGNED,
    ON_THE_WAY,
    ON_SITE,
    COMPLETED,
}

MASTER_ALLOWED_TRANSITIONS = {
    ASSIGNED: {ON_THE_WAY},
    ON_THE_WAY: {ON_SITE},
    ON_SITE: {COMPLETED},
    COMPLETED: set(),
    PAID: set(),
}

REPORT_UPLOAD_ALLOWED_STATUSES = {
    ON_SITE,
    COMPLETED,
    PAID,
}

MASTER_AVAILABLE_ORDER_STATUSES = {
    SEARCHING,
    PENDING_USER_CONFIRMATION,
}

USER_ACTIVE_ORDER_STATUSES = {
    SEARCHING,
    PENDING_USER_CONFIRMATION,
    ASSIGNED,
    ON_THE_WAY,
    ON_SITE,
}

USER_DONE_ORDER_STATUSES = {
    COMPLETED,
    PAID,
}